[general]
units = "metric"
gravity = 9.81
water_density = 1025.9
water_depth = 2000.0

[line_types.polyester]
diameter        = 0.233
mass_per_length = 53.7
youngs_modulus = 9.15e9
internal_diameter = 0.0
internal_contents_density = 0.0

[line_types.chain]
diameter        = 0.127
mass_per_length = 293.98
youngs_modulus = 7.76e10
internal_diameter = 0.0
internal_contents_density = 0.0

[lines.Line1]
top_position    = [    3,    3, -25 ]
bottom_position = [ 1000, 1000, -2000 ]
segments = [
    {line_type="chain", length=100, num_elements=10},
    {line_type="polyester", length=2600, num_elements=20},
    {line_type="chain", length=100, num_elements=10},
]

[lines.Line2]
top_position    = [   -3,     3, -25 ]
bottom_position = [ -1000, 1000, -2000 ]
segments = [
    {line_type="chain", length=100, num_elements=10},
    {line_type="polyester", length=2600, num_elements=20},
    {line_type="chain", length=100, num_elements=10},
]

[lines.Line3]
top_position    = [    -3,    -3, -25 ]
bottom_position = [ -1000, -1000, -2000 ]
segments = [
    {line_type="chain", length=100, num_elements=10},
    {line_type="polyester", length=2600, num_elements=20},
    {line_type="chain", length=100, num_elements=10},
]

[lines.Line4]
top_position    = [    3,    -3, -25 ]
bottom_position = [ 1000, -1000, -2000 ]
segments = [
    {line_type="chain", length=100, num_elements=10},
    {line_type="polyester", length=2600, num_elements=20},
    {line_type="chain", length=100, num_elements=10},
]
