[package]
name = "rusty-mooring"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rusty_mooring"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module"] }
serde = "1.0.163"
serde_derive = "1.0.163"
toml = "0.5.9"

[dev-dependencies]
float-cmp = "0.9.0"
