name: Test

on:
  pull_request:
  push:

jobs:
  test:
    name: Test (Python ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run nox
        uses: wntrblm/nox@2022.8.7
        with:
          python-versions: "3.9, 3.10"
